// <auto-generated />
using Game.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Game.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210822214257_seeding_database")]
    partial class seeding_database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Game.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Japanese",
                            Title = "Japan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chinese",
                            Title = "China"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Korean",
                            Title = "Korea"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thai",
                            Title = "Thailand"
                        });
                });

            modelBuilder.Entity("Game.Data.GameData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("GameData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = 1,
                            ImgUrl = "/Images/1_1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Answer = 1,
                            ImgUrl = "/Images/1_2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Answer = 1,
                            ImgUrl = "/Images/1_3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Answer = 2,
                            ImgUrl = "/Images/2_1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Answer = 2,
                            ImgUrl = "/Images/2_2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Answer = 2,
                            ImgUrl = "/Images/2_3.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Answer = 3,
                            ImgUrl = "/Images/3_1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Answer = 3,
                            ImgUrl = "/Images/3_2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Answer = 3,
                            ImgUrl = "/Images/3_3.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Answer = 4,
                            ImgUrl = "/Images/4_1.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Answer = 4,
                            ImgUrl = "/Images/4_2.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Answer = 4,
                            ImgUrl = "/Images/4_3.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Answer = 4,
                            ImgUrl = "/Images/4_4.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
